# Generated by Django 4.2.1 on 2023-06-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue', models.TextField(verbose_name='Clue')),
                ('answer', models.CharField(max_length=50, verbose_name='Answer')),
                ('row', models.IntegerField(verbose_name='Row')),
                ('col', models.IntegerField(verbose_name='Col')),
                ('orientation', models.CharField(max_length=10, verbose_name='Orientation')),
            ],
        ),
    ]
